FROM debian:stable
RUN apt-get update && apt-get install -y \
	jq \
	mosquitto-clients \
	curl \
  && rm -rf /var/lib/apt/lists/*

COPY ./src/scripts/* /SMA-Monitor/
RUN chmod +x /SMA-Monitor/*.sh

ENTRYPOINT ["/SMA-Monitor/run.sh"]
